version: '3.7'
services:
  app:
      build: .
      container_name: ssr-app
      restart: always
      ports:
        - 8081:8081
      volumes:
        - .:/app
      links: 
        - mongodb
      networks: 
        - backend

  mongodb:
      restart: always
      image: mongo
      container_name: mongo-cont
      ports:
        - "27017:27017"
      volumes:
        - ~/mongo_data:/data/db
      networks: 
        - backend
networks:
  backend:
    driver: "bridge"

